[package]
description = "CosmWasm integration testing for Osmosis"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "osmosis-test-tube"
repository = "https://github.com/osmosis-labs/test-tube"
version = "15.1.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

exclude = [
  "osmosis",
  "test_artifacts",
]

[features]
backtraces = ["cosmwasm-std/backtraces", "osmosis-std/backtraces", "test-tube/backtraces"]

[dependencies]
base64 = "0.13.0"
cosmrs = {version = "0.9.0", features = ["cosmwasm"]}
cosmwasm-std = "1.1.2"
osmosis-std = { git = "https://github.com/apollodao/osmosis-rust.git", rev = "cd3e84201b08d168ee848acbebc85b1da7cab3fa" }
prost = "0.11.0"
serde = "1.0.144"
serde_json = "1.0.85"
test-tube = {version = "0.1.2", path = "../test-tube"}
thiserror = "1.0.34"

[build-dependencies]
bindgen = "0.60.1"

[dev-dependencies]
cw1-whitelist = "0.15.0"
rayon = "1.5.3"
